-- 코드를 입력하세요
SELECT
    FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FOOD_TYPE IN (
    SELECT
        FOOD_TYPE
    FROM REST_INFO
    GROUP BY FOOD_TYPE -- 식당을 음식종류별로 그룹화한 후
    HAVING FAVORITES = MAX(FAVORITES) -- 각 음식종류별로 즐겨찾기수가 가장 큰 식당만 조회
)
ORDER BY FOOD_TYPE DESC